### ISSUE TITLE
further development of a complete lyrics package for emacs

### ISSUE THREAD

**Issue by mihaiolteanu** [lepisma/read-lyrics.el#5]
Is this still under development?

If not, please consider using and/or contributing to [versuri](https://github.com/mihaiolteanu/versuri).

I also know about [lyrics.el](https://github.com/emacs-pe/lyrics.el), but that also seems to be abandoned and incomplete.

**Comment by lepisma** [comment]
I don't actively develop it, but use it relatively actively. Since I might not add code here, I will see if I can contribute in versuri later on. Thanks :)

**Comment by mihaiolteanu** [comment]
Oh, nice. Now you've made me curious. Do you combine it with a music player to get the lyrics for the currently playing song, or something similar?

**Comment by lepisma** [comment]
yes. [this](https://github.com/lepisma/bbq) and [here](https://github.com/lepisma/rogue/blob/master/packages.el#L390-L400). I used your lastfm package in my player for scrobbling and stuff :)
